# Generated by Django 3.0.4 on 2020-04-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_infor',
        ),
    ]
