# Generated by Django 3.0.4 on 2020-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templateapp', '0002_delete_user_infor'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_dob', models.DateField()),
                ('user_weight', models.FloatField(default=None)),
                ('user_height', models.FloatField(default=None)),
                ('user_gender', models.CharField(default=None, max_length=30)),
                ('user_goal', models.CharField(default=None, max_length=30)),
                ('user_profession', models.CharField(default=None, max_length=30)),
                ('user_lifestyle', models.CharField(default=None, max_length=30)),
                ('user_medicalhistory', models.CharField(default=None, max_length=30)),
                ('user_foodprefer', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
