# Generated by Django 3.0.4 on 2020-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0003_user_infor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=30)),
                ('user_email', models.EmailField(default=None, max_length=254)),
                ('user_password', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
