# Generated by Django 3.0.4 on 2020-05-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
