# Generated by Django 3.0.4 on 2020-05-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0008_user_infor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infor',
            name='username',
        ),
    ]
