# Generated by Django 3.0.4 on 2020-05-04 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0011_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infor',
            name='user',
        ),
    ]
