# Generated by Django 3.0.4 on 2020-05-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0015_auto_20200505_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infor',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
