# Generated by Django 3.0.4 on 2020-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0016_auto_20200505_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infor',
            name='user_dob',
            field=models.CharField(max_length=30),
        ),
    ]
