# Generated by Django 3.0.4 on 2020-05-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0017_auto_20200505_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infor',
            name='user_height',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_infor',
            name='user_weight',
            field=models.CharField(max_length=30),
        ),
    ]
