# Generated by Django 3.0.4 on 2020-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0018_auto_20200505_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infor',
            name='user_foodprefer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_infor',
            name='user_gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_infor',
            name='user_goal',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_infor',
            name='user_lifestyle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_infor',
            name='user_medicalhistory',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_infor',
            name='user_profession',
            field=models.CharField(max_length=30),
        ),
    ]
