# Generated by Django 3.0.4 on 2020-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0020_user_infor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infor',
            name='user_gender',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=30),
        ),
    ]
