# Generated by Django 3.0.4 on 2020-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0021_auto_20200506_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infor',
            name='user_gender',
            field=models.CharField(max_length=30),
        ),
    ]
