# Generated by Django 3.0.4 on 2020-05-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0030_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pi',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
