# Generated by Django 3.1.4 on 2020-12-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateapp', '0033_auto_20200509_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
